name: Docker Image CI

on:
  push:
    branches:
      - peter
jobs:
  push:
    runs-on: ubuntu-latest
#     if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: azure/docker-login@v1
        with:
          login-server: rickyappreg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t rickyappreg.azurecr.io/ricky_app:${{ github.run_number }}
          docker push rickyappreg.azurecr.io/ricky_app:${{ github.run_number }}